# Default values for akka-seeds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: !!int 2
image:
  repository: docker.grandsys.com/inu/akka-seeds
  tag: 2.5.3
  pullPolicy: Always
service:
  name: akka-seeds
  externalPort: 2552
  internalPort: 2552
seedHostNamePrefix: akka-seed
clusterHttpManPort: 7878
imagePullSecret: grandsys
actorsystem: ClusterSystem
resources:
  limits:
    memory: 1Gi
