---
{{- $membersPath := printf "/members/akka.tcp://%s@${POD_NAME}.%s:%v" .Values.actorsystem (include "urisuffix" .) .Values.seedPort }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
data:
  pre-stop.sh: |-
    /usr/bin/curl -i -X DELETE http://127.0.0.1:{{ .Values.clusterHttpManPort }}{{ $membersPath }}
    /usr/bin/curl -i -X PUT -F 'operation=Down' http://127.0.0.1:{{ .Values.clusterHttpManPort }}{{ $membersPath }}
  healthz: |-
    /usr/bin/curl -i http://127.0.0.1:{{ .Values.clusterHttpManPort }}{{ $membersPath }}
  prod.conf: |-
    include "application"

    cluster {
      name = {{ .Values.actorsystem }}
      port = {{ .Values.seedPort }}
    }

    akka {
      loglevel = "INFO"
      
      actor {
        serialize-messages = on

        serializers {
          proto = "akka.remote.serialization.ProtobufSerializer"
        }

        serialization-bindings {
          "com.trueaccord.scalapb.GeneratedMessage" = proto
        }
      }

      remote {
        log-remote-lifecycle-events = off
        netty.tcp {
          hostname = ${?POD_NAME}.{{ include "urisuffix" . }}
        }
      }

      cluster {
        {{- $replicas := ( .Values.replicaCount | int ) }}
        {{- $fmt := printf "akka.tcp://%s@%s-%%d.%s:%d" .Values.actorsystem .Values.seedHostNamePrefix (include "urisuffix" .) ( .Values.seedPort | int ) }}
        seed-nodes = [
        {{- range $e := until $replicas }}
          "{{ printf $fmt $e }}"
          {{- if ne $replicas (add1 $e) -}}
          ,
          {{- end }}
        {{- end }}
        ]

        log-info = off
        metrics.enabled = off

        http {
          management {
            hostname = "127.0.0.1"
            port = {{ .Values.clusterHttpManPort }}
          }
        }
      }
    }