---
{{- $membersPath := printf "/members/akka.tcp://%s@${POD_NAME}.%s:%v" .Values.actorsystem.name (include "urisuffix" .) .Values.service.internalPort }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
data:
  pre-stop.sh: |
    /usr/bin/curl -i -X DELETE http://127.0.0.1:{{ .Values.clusterHttpManPort }}{{ $membersPath }}
  healthz.sh: |
    /usr/bin/curl -i http://127.0.0.1:{{ .Values.clusterHttpManPort }}{{ $membersPath }}
