---
{{- $membersPath := printf "/members/akka.tcp://%s@${POD_NAME}.%s:%v" .Values.actorsystem.name (include "urisuffix" .) .Values.service.internalPort }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
data:
  pre-stop.sh: |
    /usr/bin/curl -i -X DELETE http://127.0.0.1:{{ .Values.clusterHttpManPort }}{{ $membersPath }}
    /usr/bin/curl -i -X PUT -F 'operation=Down' http://127.0.0.1:{{ .Values.clusterHttpManPort }}{{ $membersPath }}
  healthz.sh: |
    /usr/bin/curl -i http://127.0.0.1:{{ .Values.clusterHttpManPort }}{{ $membersPath }}
  akka.conf: |
    include "application"
    akka {

      loglevel = "INFO"

      remote {
        netty.tcp {
          hostname = ${?POD_NAME}.{{ include "urisuffix" . }}
          prot = {{ .Values.service.internalPort }}
        }
      }

      cluster {
        log-info = on

        http {
          management {
            hostname = 127.0.0.1
            port = {{ .Values.clusterHttpManPort }}
          }
        }
      }
    }
    cluster {
      seed-nodes = "{{ .Values.seedHostNamePrefix }}-0.{{ include "urisuffix" . }}"
      name = "{{ .Values.actorsystem.name }}"
    }