---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  ports:
  - port: {{ .Values.seedPort }}
    protocol: TCP
    targetPort: {{ .Values.seedPort }}
  selector:
{{ include "labels.seed" . | indent 4 }}      
  clusterIP: None
