---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ .Values.seedHostNamePrefix }}
spec:
  serviceName: {{ .Values.service.name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: seed
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        component: seed
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: configs
          configMap:
            name: {{ template "fullname" . }}
      containers:
      - name: seed
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          protocol: TCP
        - containerPort: {{ .Values.clusterHttpManPort }}
          protocol: TCP
        env:
        - name: AB_OFF
          value: 'true'
        - name: MAN_PORT
          value: '{{ .Values.clusterHttpManPort }}'
        - name: SEED_NODES
          value: '{{ .Values.seedHostNamePrefix }}-0.{{ include "urisuffix" . }}'
        - name: SEED_PORT
          value: '{{ .Values.service.internalPort }}'
        - name: CLUSTER_NAME
          value: '{{ .Values.actorsystem.name }}'
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command:
          - "/bin/sh"
          - "-c"
          - "HOST_NAME=${POD_NAME}.{{ include "urisuffix" . }} /deployments/run-java.sh"
        volumeMounts:
          - name: configs
            mountPath: /opt/probe/bin
        readinessProbe:
          exec:
            command:
              - sh
              - /opt/probe/bin/healthz
          initialDelaySeconds: 7
          periodSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
