---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ .Values.seedHostNamePrefix }}
spec:
  serviceName: {{ .Values.service.name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: seed
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/extras-confMap: {{ include (print $.Template.BasePath "/configMap.yaml") . | sha256sum }}
      labels:
        component: seed
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: extras
          configMap:
            name: {{ template "fullname" . }}
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{- end }}
      containers:
      - name: seed
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          protocol: TCP
        - containerPort: {{ .Values.clusterHttpManPort }}
          protocol: TCP
        env:
        - name: AB_OFF
          value: 'true'
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: JAVA_OPTIONS
          value: >-
            -Dconfig.file=/extras/akka.conf
        volumeMounts:
          - name: extras
            mountPath: /extras
        livenessProbe:
          tcpSocket:
            port: {{ .Values.service.internalPort }}
        readinessProbe:
          exec:
            command:
              - sh
              - /extras/healthz.sh
          initialDelaySeconds: 7
          periodSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
